config/routes.rb
Magfolio::Application.routes.draw do

  

  get "add_post/add_mnenie"

  get "add_post/add_akciya"

  get "add_post/add_presentation"

  get "top/top_specialist"

  get "presentation/index"

  get "presentation/reserv_page1"

  get "presentation/reserv_page2"

  get "presentation/reserv_page3"

  get "top/top_mneniy"

  get "top/top_presentation"

  get "top/top_catalogov"

  get "top/top_user"

  get "userpg/user1"

  get "about1/xxx4"
  get "about1/xxx1"

  get "about1/xxx2"

  get "about1/xxx3"

  get "cartography/:catalog_id/show" => "cartography#show", :as => "catalog_map_show"
  
  resources :izbrannoes

  resources :business_deals

  resources :pictures
  
  match 'order/:id/comment/add' => 'orders#add_comment_to_last_state', :as => 'add_comment_to_last_state'
  match 'order/:id/getstate' => 'orders#getstate', :as => :getstate
  match 'order/:id/editstate' => 'orders#editstate', :as => :editstate
  match 'order/:id' => 'orders#catalog_order', :as => :catalog_order
  match 'orders/catalog/:catalog_id' => 'orders#catalog_orders', :as => :catalog_orders
  match 'orders/:customer_id' => 'orders#index', :as => :customer_orders
  match 'orders/:customer_id/catalog/:catalog_id' => 'orders#customer_orders_for_catalog', :as => :customer_orders_for_catalog
  match 'order/:customer_id/show/:id' => 'orders#show', :as => :show_order
  match 'order/new/:stage' => 'orders#new', :as => :make_order

  match '/mycart/destroy' => "carts#destroy", :as => :destroy_cart
  match '/mycart/:catalog_id/destroy/:product_id' => "carts#destroy_from_cart", :as => :destroy_from_cart
  match '/mycart/edit/payment/:payment' => "carts#edit_payment_order_options", :as => :edit_payment_order_options
  match '/mycart/edit/delivery/:delivery' => "carts#edit_delivery_order_options", :as => :edit_delivery_order_options
  match '/mycart/edit/products' => "carts#edit_products", :as => :edit_mycart_products
  match '/mycart' => "carts#show", :as => :show_mycart
  
  match 'catalog/:id/setfilter' => "catalogs#setfilter", :as => :catalog_set_filter
  match 'catalog/:id/mappopup' => "catalogs#mappopup", :as => :catalog_map_popup  
  match 'catalog/:catalog_id/product/:product_id/cart/add' => 'carts#add', :as => :add_to_cart
  match 'catalogs/myfind' => 'catalogs#myfind', :as => :catalogs_find
  match '/search' => 'catalogs#search', :as => :search
  match 'catalogs/:id/setcoordinate' => 'catalogs#setcoordinate', :as => :catalog_setcoordinate
  match 'catalogs/:id/loadmap' => 'catalogs#loadmap', :as => :loadmap
  match 'catalogs/indexload' => 'catalogs#indexload', :as => :index_load
  
  resources :catalogs do
    resources :products do
      resources :product_pictures
    end
    resources :statistics
  end

  match 'sessions/edituser/:reset_password_token' => 'sessions#edituser', :as => :edit_user_with_rptoken
  match 'sessions/updatepassword/:reset_password_token' => 'sessions#updatepassword', :as => :session_updatepassword
  match 'sessions/sendresetpasswordmail' => 'sessions#sendresetpasswordmail', :as => :sendresetpasswordmail
  match '/password/reset' => 'sessions#resetpassword', :as => :resetpassword
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  
  resources :users
  
  resources :sessions

  resources :locations

  match 'businesstype/getbusinesstypes' => 'business_types#getbusinesstypes'
  match 'businesstype/ajaxcreate' => 'business_types#ajaxcreate'
  resources :business_types

  match 'signup/getbusinessdeals' => 'signup#getbusinessdeals', :as => :getbusinessdeals
  match 'signup/setbusinessdeal' => 'signup#setbusinessdeal', :as => :setbusinessdeal
  match 'signup' => 'signup#stage1', :as => :signup
  match 'signup/stage1' => 'signup#stage1', :as => :signup_stage1
  match 'signup/stage2' => 'signup#stage2', :as => :signup_stage2
  match 'signup/stage3-free' => 'signup#stage3free', :as => :signup_stage3_free
  match 'signup/stage3-pay' => 'signup#stage3pay', :as => :signup_stage3_pay
  match 'signup/bestpictureupload' => 'signup#bestpictureupload', :as => :bestpictureupload
  match 'signup/:id/bestpictureurl' => 'signup#bestpictureurl', :as => :bestpictureurl
  match 'signup/:id/logoupload' => 'signup#logoupload', :as => :logoupload
  
  match 'about' => 'about#index', :as => :about

  match 'cities' => 'cities#index', :as => :cities
  
  match 'city/:city_name/service/:service_kind' => 'catalogs#index', :as => :search_city_name_service_kind
  match 'service/:service_kind' => 'catalogs#index', :as => :search_service_name
  match 'city/:city_name/product/:product_kind' => 'catalogs#index', :as => :search_city_name_product_kind
  match 'product/:product_kind' => 'catalogs#index', :as => :search_product_name
  match 'city/:city_name' => 'catalogs#index', :as => :search_city_name
  
  match '/:shortcut_name' => 'catalogs#show', :as => :shortcut_catalog
  root :to => "catalogs#index"
  

  
end

app/controllers/cartography_controller.rb
class CartographyController < ApplicationController

  def show
    @onload = 'init()'
    @body_css_class = "perma cities"
    @catalog = Catalog.find(params[:catalog_id])
    if @catalog.lat.nil? && @catalog.lng.nil?
      @lon = 40.1257947
      @lat = 45.853046010913
    else
      @lon = @catalog.lng
      @lat = @catalog.lat
    end
    if current_user_self?
      render 'show', :layout => true
    else
      redirect_to root_url, :alert => t('cartography.msg_add_marker_on_map_non_self_alert')
    end
  rescue
    msg = "#{t("default.rescue_error_in_controllers")} CartographyController: #{$!}"
    redirect_to root_url, :alert => msg
  end
  
end

app/views/cartography/_map-cloudmade.html.erb
<div id="cm-example" style="width: 900px; height: 630px"></div>
<div id="message">Drag or click the map.</div>

<a id="add_coord_to_catalog" href="#coord_to_catalog" style="display:none">&nbsp;</a>
<div style="display:none">
  <div id="coord_to_catalog">
    <h2>Координаты точки</h2>
    <p>Широта:</p>
    <p>Долгота:</p>
  </div>
</div>

<script type="text/javascript" src="http://tile.cloudmade.com/wml/0.4/web-maps-lite.js"></script>
<script type="text/javascript">//<![CDATA[
	var cloudmade = new CM.Tiles.CloudMade.Web({key: '8ee2a50541944fb9bcedded5165f09d9'});
	var map = new CM.Map('cm-example', cloudmade);
	map.addControl(new CM.LargeMapControl());
	map.setCenter(new CM.LatLng(45.8533228, 40.1257947), 14);
	
	function displayMessage(msg) {
		document.getElementById('message').innerHTML = msg;
	}
	
	CM.Event.addListener(map, 'click', function(latlng) {
		displayMessage("Место1" + latlng.toString(4));
		$("a#add_coord_to_catalog").click();
	});
	
//]]></script>

app/views/cartography/_map.html.erb
<% content_for :head do %>
  <script src="http://www.openlayers.org/api/OpenLayers.js"></script>
  
  <script type="text/javascript">
    var map;
    var layer, markers;
    var icon ;
    var currentPopup;
    
    OpenLayers.Control.Click = OpenLayers.Class(OpenLayers.Control, {                
      defaultHandlerOptions: {
          'single': true,
          'double': false,
          'pixelTolerance': 0,
          'stopSingle': false,
          'stopDouble': false
      },
      initialize: function(options) {
        this.handlerOptions = OpenLayers.Util.extend({}, this.defaultHandlerOptions);
        OpenLayers.Control.prototype.initialize.apply(this, arguments); 
        this.handler = new OpenLayers.Handler.Click(  this, 
                                                      {'click': this.trigger},  
                                                      this.handlerOptions
                                                    );
      }, 
      trigger: function(e) {
        var lonlat = map.getLonLatFromViewPortPx(e.xy).transform(
            new OpenLayers.Projection("EPSG:900913"),new OpenLayers.Projection("EPSG:4326"));
  	    // alert("Устанавливаю координаты\n" + lonlat.lat + " N, " + lonlat.lon + " E");
        $.ajax({
          type: "PUT",
          url: '<%= catalog_setcoordinate_path(@catalog) %>',
          data: { longitude: lonlat.lon, latitude: lonlat.lat, authenticity_token: "<%= form_authenticity_token %>" },
          success: function(msg){
            if(msg == 'true'){
    			    window.location = window.location ;
    			  }else{
    			    alert('не удалось установить Ваш <%= BusinessType.find(@catalog.businesstype_id).name %> на карте, обратитесь к администрации сайта для решения этой проблемы')
    			  }
          }
        });
      }
    });

    AutoSizeFramedCloud = OpenLayers.Class(OpenLayers.Popup.FramedCloud, {
      'autoSize': true
    });

    function init(){
      map = new OpenLayers.Map('map');
      layer = new OpenLayers.Layer.OSM( "Simple OSM Map");
      map.addLayer(layer);
      map.addControl(new OpenLayers.Control.MousePosition());
      
      var popup = new OpenLayers.Layer.Text(  "text", 
                                              { location: "/catalog/<%= @catalog.id %>/mappopup" }
                                            );
      map.addLayer(popup);
      
      map.setCenter(new OpenLayers.LonLat(<%= @lon -%>, <%= @lat -%>).transform(
          new OpenLayers.Projection("EPSG:4326"),
          map.getProjectionObject()
      ), 15);
      
      var click = new OpenLayers.Control.Click();
      map.addControl(click);
      click.activate();
    }
  
    function addMarker(ll, popupClass, popupContentHTML, closeBox, overflow){
      var feature = new OpenLayers.Feature(markers, ll); 
      feature.closeBox = closeBox;
      feature.popupClass = popupClass;
      feature.data.popupContentHTML = popupContentHTML;
      feature.data.overflow = (overflow) ? "auto" : "hidden";
      var marker = feature.createMarker();
      var markerClick = function (evt) {
        if (this.popup == null){
          this.popup = this.createPopup(this.closeBox);
          map.addPopup(this.popup);
          this.popup.show();
        }else{
          this.popup.toggle();
        }
        currentPopup = this.popup;
        OpenLayers.Event.stop(evt);
      };
      marker.events.register("mousedown", feature, markerClick);
      markers.addMarker(marker);
    }

  </script>  
  <style type="text/css">
    .catalogmap{
        width: 900px;
        height: 600px;
        border: 1px solid #ccc;
    }
    #tags{display: none;}
    #docs p {margin-bottom: 0.5em;}
  </style>
<% end %>

<div id="tags"></div>
<div id="map" class="catalogmap"></div>
<div id="docs"></div>

app/views/cartography/index.html.erb
<div class="card-perma">
  <div class="cardcap-perma">
    <img alt="Card-top-perma" src="/images/card-top-perma.png">
  </div>
  <div class="cardcontent-perma">
    <div class="cardtools">
      <div class="printpage">
        <a href="#" class="print" target="_blank">
          Рейтинг
        </a>
      </div>
      <div class="listing">
        <span class="favorite_links" data-listing-id="8805">
          <a href="/favorites/8805/remove.js" class="favorites remove_from_favorites" onclick="return false" style="display: none; ">Удалить из избранного</a>
          <a href="/favorites/8805/add.js" class="favorites add_to_favorites" onclick="return false" style="">Добавить в избранное</a>
        </span>  
      </div>
    </div>
      <h2>Карта</h2>
      <p>
        Вид бизнеса: 
        <strong>Карта</strong><br />
        Расположен в 
        <strong>
          <a href="/chicago">Карта></a>
        </strong><br />
        E-mail: 
        <strong>
        </strong>
      </p>
      <div class="map">
        <%= render :partial => 'map' %>
      </div>
    <div class="action">
      <h2>Вам понравилось? Свяжитесь с .</h2>
      <h3>
      </h3>
    </div>
  </div>
  <div class="cardcap-perma">
    <img alt="Card-bottom-perma" src="/images/card-bottom-perma.png">
  </div>
</div>

app/views/cartography/show.html.erb
<div class="card-perma">
  <div class="cardcap-perma">
    <img alt="Card-top-perma" src="/images/card-top-perma.png">
  </div>
  <div class="cardcontent-perma">
    <div class="cardtools">
      <div class="printpage">
        <a href="#" class="print" target="_blank">
          Рейтинг
          <%= @catalog.rating %>
        </a>
      </div>
      <div class="listing">
        <span class="favorite_links" data-listing-id="8805">
          <a href="/favorites/8805/remove.js" class="favorites remove_from_favorites" onclick="return false" style="display: none; ">Удалить из избранного</a>
          <a href="/favorites/8805/add.js" class="favorites add_to_favorites" onclick="return false" style="">Добавить в избранное</a>
        </span>  
      </div>
    </div>
      <% if /missing/ =~ @catalog.logo.url(:thumb) %>
      <% else %>
      <%= image_tag @catalog.logo.url(:thumb), :align => 'right' %>
      <% end %>
      <h2><%= @catalog.company_name %></h2>
      <p>
        Вид бизнеса: 
        <strong><%= BusinessType.find(@catalog.businesstype_id).name %></strong><br />
        Расположен в 
        <strong>
          <a href="/chicago"><%= Location.find(@catalog.location_id).name %></a>
        </strong><br />
        E-mail: 
        <strong>
          <a href="mailto:<%= @catalog.email -%>?subject=Вопросы о каталоге <%= @catalog.company_name -%>"><%= @catalog.email %></a>
        </strong>
      </p>
      <% unless @catalog.company_description.blank? %>
      <%= render :inline => @catalog.company_description %>
      <% end %>
      <div class="map">
        <%= render :partial => 'map' %>
      </div>
    <div class="action">
      <h2>Вам понравилось? Свяжитесь с <%= @catalog.company_name %>.</h2>
      <h3>
          <a href="mailto:<%= @catalog.email %>"><%= @catalog.email %></a>
          •
          <a href="<%= @catalog.company_url %>"><%= @catalog.company_url %></a>
      </h3>
    </div>
  </div>
  <div class="cardcap-perma">
    <img alt="Card-bottom-perma" src="/images/card-bottom-perma.png">
  </div>
</div>